services:
  back:
    image: flexbox-sandbox-back:latest
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  auth:
    build: ./auth
    depends_on:
      - db
    ports:
      - "8081:8080"
    command: "start-dev --import-realm"

