services:
#  back:
#    build:
#      context: backend
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init:/docker-entrypoint-initdb.d

